services:
  - type: web
    name: agrismart-backend
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt && python create_model.py
    startCommand: gunicorn app:app
    envVars:
      - key: WEATHER_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
